[package]
name = "embassy-example"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
embedded-hal = "1"

rtt-target = { version = "0.5" }
panic-rtt-target = { version = "0.1" }
critical-section = "1"

embassy-sync = { version = "0.6.0" }
embassy-time = { version = "0.3.2" }
embassy-time-driver = { version = "0.1" }

[dependencies.once_cell]
version = "1"
default-features = false
features = ["critical-section"]

[dependencies.embassy-executor]
version = "0.6.0"
features = [
    "arch-cortex-m",
    "executor-thread",
    "executor-interrupt",
    "integrated-timers",
]

[dependencies.va416xx-hal]
path = "../../va416xx-hal"
features = ["va41630"]

[features]
default = ["ticks-hz-1_000"]
ticks-hz-1_000 = ["embassy-time/tick-hz-1_000"]
ticks-hz-32_768 = ["embassy-time/tick-hz-32_768"]
